// src/views/PriceList.vue
<template>
  <div class="px-2 py-3 sm:px-0 sm:py-6">
    <div class="border-4 border-dashed border-gray-200 rounded-lg p-3 sm:p-6">
      <!-- Header -->
      <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 mb-4 sm:mb-6">
        <h2 class="text-xl sm:text-2xl font-bold text-gray-900">Price List</h2>
      </div>

      <!-- Mark Ordered Modal -->
      <ActionModal
        :is-open="showOrderModal"
        :title="`Mark Ordered: ${orderItem?.item_name}`"
        variant="green"
        :loading="inventoryStore.loading"
        confirm-text="Mark Ordered"
        @close="closeOrderModal"
        @cancel="closeOrderModal"
        @confirm="confirmMarkAsOrdered"
      >
        <div class="space-y-4">
          <div class="bg-green-50 border border-green-200 rounded-md p-3">
            <div class="flex items-center gap-2 mb-2">
              <CalendarIcon class="w-4 h-4 text-green-500" />
              <span class="text-sm font-medium text-green-800"> Set Order Date </span>
            </div>
            <p class="text-sm text-green-700">
              This will mark the item as ordered and track its pending status.
            </p>
          </div>

          <FormField v-model="orderDate" type="date" label="Order Date" :required="true" />
          <div class="bg-green-50 border border-green-200 rounded-md p-3">
            <div class="flex items-center gap-2 mb-2">
              <ClockIcon class="w-4 h-4 text-green-500" />
              <span class="text-sm font-medium text-green-800"> Back Order Item </span>
            </div>
            <div class="flex items-start gap-3">
              <input
                id="back-order"
                v-model="backOrder"
                type="checkbox"
                class="mt-1 h-4 w-4 text-green-600 focus:ring-green-500 border-gray-300 rounded"
              />
              <div class="flex-1">
                <label for="back-order" class="text-sm font-medium text-gray-700">
                  Mark as back order
                </label>
                <p class="text-sm text-gray-500 mt-1">Check this to mark the item as back order.</p>
              </div>
            </div>
          </div>
        </div>
      </ActionModal>

      <!-- Edit Remark Modal -->
      <ActionModal
        :is-open="showEditRemarkModal"
        :title="`Edit Remark: ${editingItem?.item_name}`"
        variant="green"
        :loading="inventoryStore.loading"
        confirm-text="Save Remark"
        :disabled="!isRemarkChanged"
        @close="closeEditRemarkModal"
        @cancel="closeEditRemarkModal"
        @confirm="confirmSaveRemark"
      >
        <div class="space-y-4">
          <div class="bg-blue-50 border border-blue-200 rounded-md p-3">
            <div class="flex items-center gap-2 mb-2">
              <CogIcon class="w-4 h-4 text-blue-500" />
              <span class="text-sm font-medium text-blue-800"> Update Item Information </span>
            </div>
            <p class="text-sm text-blue-700">
              Add notes such as last purchase price, supplier information, or other relevant
              details.
            </p>
          </div>

          <FormField
            v-model="newRemark"
            type="textarea"
            label="Remark"
            :rows="3"
            placeholder="Enter remark (e.g., last purchase price, supplier info)..."
          />
        </div>
      </ActionModal>

      <!-- Search Bar and Filters -->
      <div class="mb-4 sm:mb-6 space-y-4">
        <SearchInput v-model="searchQuery" placeholder="Search items..." />

        <!-- Filter Controls -->
        <div class="flex flex-wrap gap-3">
          <div class="flex items-center gap-2">
            <input
              id="filter-ordered"
              v-model="showOrderedOnly"
              type="checkbox"
              class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
            />
            <label for="filter-ordered" class="text-sm font-medium text-gray-700">
              Show only items with order date
            </label>
          </div>
        </div>
      </div>

      <!-- Error Display -->
      <div v-if="inventoryStore.error" class="mb-4">
        <ErrorAlert :message="inventoryStore.error" />
      </div>

      <!-- Mobile Card View -->
      <div class="block lg:hidden">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 sm:px-6 border-b border-gray-200">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
              Items ({{ sortedAndFilteredItems.length }})
            </h3>
          </div>

          <LoadingSpinner
            v-if="inventoryStore.loading && sortedAndFilteredItems.length === 0"
            message="Loading items..."
          />

          <EmptyState
            v-else-if="sortedAndFilteredItems.length === 0"
            icon="box"
            title="No items found"
            :description="searchQuery ? 'Try adjusting your search terms.' : 'No items available.'"
          />

          <div v-else class="divide-y divide-gray-200">
            <div v-for="item in pagination.paginatedItems.value" :key="item.id" class="px-4 py-4">
              <div class="space-y-3">
                <!-- Item Header -->
                <div class="flex items-center justify-between">
                  <h4 class="text-sm font-medium text-gray-900 truncate flex-1 mr-2">
                    {{ item.item_name }}
                  </h4>
                </div>

                <!-- Item Details -->
                <div class="text-sm space-y-1">
                  <div class="flex items-baseline gap-2">
                    <span class="text-gray-500 flex-shrink-0">Current Stock:</span>
                    <span class="font-medium text-gray-900">
                      {{ item.quantity }} {{ item.unit }}
                    </span>
                  </div>
                  <div v-if="item.order_date" class="flex items-baseline gap-2">
                    <span v-if="item.back_order" class="text-gray-500 flex-shrink-0"
                      >Back Ordered:</span
                    >
                    <span v-else class="text-gray-500 flex-shrink-0">Ordered:</span>
                    <span class="font-medium text-blue-600">
                      {{ formatDate(item.order_date) }}
                    </span>
                  </div>
                  <div v-else-if="item.non_order_reason" class="flex items-baseline gap-2">
                    <span class="text-gray-500 flex-shrink-0">Reason:</span>
                    <ReasonBadge :reason="item.non_order_reason" size="sm">
                      {{ item.non_order_reason }}
                    </ReasonBadge>
                  </div>
                  <div class="flex items-start gap-2">
                    <span class="text-gray-500 flex-shrink-0">Remark:</span>
                    <span class="font-medium text-gray-900 whitespace-pre-wrap">
                      {{ item.remark || 'No remark' }}
                    </span>
                  </div>
                </div>

                <!-- Actions -->
                <div class="pt-2 border-t border-gray-100">
                  <ActionButtonGroup
                    :actions="getItemActions(item)"
                    size="sm"
                    :loading="inventoryStore.loading"
                    @action-click="(actionKey) => handleActionClick(actionKey, item)"
                    class="w-full"
                  />
                </div>
              </div>
            </div>
          </div>

          <!-- Mobile Pagination -->
          <TablePagination
            v-if="pagination.totalPages.value > 1"
            :current-page="pagination.currentPage.value"
            :total-pages="pagination.totalPages.value"
            :items-per-page="pagination.itemsPerPage.value"
            :total-items="sortedAndFilteredItems.length"
            :start-index="pagination.startIndex.value"
            :end-index="pagination.endIndex.value"
            :show-items-per-page-selector="false"
            @page-change="pagination.goToPage"
            @items-per-page-change="pagination.updateItemsPerPage"
          />
        </div>
      </div>

      <!-- Desktop Table View -->
      <div class="hidden lg:block">
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 sm:px-6 border-b border-gray-200">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
              Items ({{ sortedAndFilteredItems.length }})
            </h3>
          </div>

          <LoadingSpinner
            v-if="inventoryStore.loading && sortedAndFilteredItems.length === 0"
            message="Loading items..."
          />

          <EmptyState
            v-else-if="sortedAndFilteredItems.length === 0"
            icon="box"
            title="No items found"
            :description="searchQuery ? 'Try adjusting your search terms.' : 'No items available.'"
          />

          <div v-else class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
              <SortableTableHeader
                :columns="tableColumns"
                :sort-config="sortConfig"
                @sort-change="toggleSort"
              />
              <tbody class="bg-white divide-y divide-gray-200">
                <tr
                  v-for="item in pagination.paginatedItems.value"
                  :key="item.id"
                  class="hover:bg-gray-50"
                >
                  <td class="px-6 py-4 text-sm font-medium text-gray-900 min-w-0 max-w-xs">
                    <div class="break-words">{{ item.item_name }}</div>
                    <!-- Show order status if item has order date -->
                    <div v-if="item.order_date" class="text-xs text-blue-600 mt-1">
                      <span v-if="item.back_order" class="inline-flex items-center gap-1">
                        <ClockIcon class="w-3 h-3" />
                        Back Ordered: {{ formatDate(item.order_date) }}
                      </span>
                      <span v-else class="inline-flex items-center gap-1">
                        <CalendarIcon class="w-3 h-3" />
                        Ordered: {{ formatDate(item.order_date) }}
                      </span>
                    </div>
                    <!-- Show non-order reason if set -->
                    <div v-else-if="item.non_order_reason" class="text-xs mt-1">
                      <ReasonBadge :reason="item.non_order_reason" size="sm">
                        {{ item.non_order_reason }}
                      </ReasonBadge>
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {{ item.quantity }} {{ item.unit }}
                  </td>
                  <td class="px-6 py-4 text-sm text-gray-900 max-w-md">
                    <div
                      class="break-words whitespace-pre-wrap"
                      :title="item.remark || 'No remark'"
                    >
                      {{ item.remark || 'No remark' }}
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                    <ActionButtonGroup
                      :actions="getItemActions(item)"
                      size="sm"
                      :loading="inventoryStore.loading"
                      @action-click="(actionKey) => handleActionClick(actionKey, item)"
                    />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <!-- Desktop Pagination -->
          <TablePagination
            :current-page="pagination.currentPage.value"
            :total-pages="pagination.totalPages.value"
            :items-per-page="pagination.itemsPerPage.value"
            :total-items="sortedAndFilteredItems.length"
            :start-index="pagination.startIndex.value"
            :end-index="pagination.endIndex.value"
            :show-items-per-page-selector="true"
            @page-change="pagination.goToPage"
            @items-per-page-change="pagination.updateItemsPerPage"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import CalendarIcon from '@/components/icons/CalendarIcon.vue'
import ClockIcon from '@/components/icons/ClockIcon.vue'
import CogIcon from '@/components/icons/CogIcon.vue'
import ActionButtonGroup, {
  type ActionButtonGroupAction,
} from '@/components/ui/ActionButtonGroup.vue'
import ActionModal from '@/components/ui/ActionModal.vue'
import EmptyState from '@/components/ui/EmptyState.vue'
import ErrorAlert from '@/components/ui/ErrorAlert.vue'
import FormField from '@/components/ui/FormField.vue'
import LoadingSpinner from '@/components/ui/LoadingSpinner.vue'
import ReasonBadge from '@/components/ui/ReasonBadge.vue'
import SearchInput from '@/components/ui/SearchInput.vue'
import SortableTableHeader from '@/components/ui/SortableTableHeader.vue'
import TablePagination from '@/components/ui/TablePagination.vue'
import { usePagination } from '@/composables/usePagination'
import { useInventoryStore } from '@/stores/inventory'
import type { InventoryItem } from '@/types/inventory'
import { computed, ref, watch } from 'vue'

const inventoryStore = useInventoryStore()

const searchQuery = ref<string>('')
const newRemark = ref<string>('')
const showOrderedOnly = ref<boolean>(false)

// Order modal variables
const showOrderModal = ref<boolean>(false)
const orderItem = ref<InventoryItem | null>(null)
const orderDate = ref<string>('')
const backOrder = ref<boolean>(false)

// Edit remark modal variables
const showEditRemarkModal = ref<boolean>(false)
const editingItem = ref<InventoryItem | null>(null)

// Removed openOrderActionDropdown as we use ActionButtonGroup's internal state

// Sorting configuration
const sortConfig = ref<{
  key: keyof InventoryItem | null
  direction: 'asc' | 'desc'
}>({
  key: null,
  direction: 'asc',
})

// Format date for display
const formatDate = (dateString: string): string => {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}

// Computed property for remark validation
const isRemarkChanged = computed(() => {
  if (!editingItem.value) return false
  return newRemark.value.trim() !== (editingItem.value.remark || '').trim()
})

// Order modal functions
const openOrderModal = (item: InventoryItem): void => {
  orderItem.value = item
  orderDate.value = new Date(Date.now() - new Date().getTimezoneOffset() * 60000)
    .toISOString()
    .slice(0, 10) // Today's date
  showOrderModal.value = true
  backOrder.value = false
}

const closeOrderModal = (): void => {
  showOrderModal.value = false
  orderItem.value = null
  orderDate.value = ''
  backOrder.value = false
}

const confirmMarkAsOrdered = async (): Promise<void> => {
  if (!orderItem.value || !orderDate.value) return

  // Mark ordered using the store function with selected date
  await inventoryStore.markAsOrdered(orderItem.value.id, orderDate.value, backOrder.value)

  if (!inventoryStore.error) {
    closeOrderModal()
  }
}

const clearOrderDate = async (itemId: string): Promise<void> => {
  await inventoryStore.clearOrderDate(itemId)
}

// Removed toggleOrderActionDropdown as ActionButtonGroup handles this internally

// Set non-order reason for an item
const setItemNonOrderReason = async (itemId: string, reason: string): Promise<void> => {
  await inventoryStore.setNonOrderReason(itemId, reason)
}

// Clear non-order reason for an item
const clearItemNonOrderReason = async (itemId: string): Promise<void> => {
  await inventoryStore.setNonOrderReason(itemId, null)
}

// Edit remark modal functions
const openEditRemarkModal = (item: InventoryItem): void => {
  editingItem.value = item
  newRemark.value = item.remark || ''
  showEditRemarkModal.value = true
}

const closeEditRemarkModal = (): void => {
  showEditRemarkModal.value = false
  editingItem.value = null
  newRemark.value = ''
}

const confirmSaveRemark = async (): Promise<void> => {
  if (!editingItem.value || !isRemarkChanged.value) return

  await saveRemark(editingItem.value.id)
  if (!inventoryStore.error) {
    closeEditRemarkModal()
  }
}

// Sorting and filtering logic
const sortedAndFilteredItems = computed((): InventoryItem[] => {
  let items = inventoryStore.searchItems(searchQuery.value)

  // Apply order date filter
  if (showOrderedOnly.value) {
    items = items.filter((item) => item.order_date)
  }

  if (sortConfig.value.key) {
    items = [...items].sort((a, b) => {
      const aValue = a[sortConfig.value.key as keyof InventoryItem]
      const bValue = b[sortConfig.value.key as keyof InventoryItem]

      // Handle null values (put them at the end)
      if (aValue === null && bValue === null) return 0
      if (aValue === null) return sortConfig.value.direction === 'asc' ? 1 : -1
      if (bValue === null) return sortConfig.value.direction === 'asc' ? -1 : 1

      // Handle string comparison
      if (typeof aValue === 'string' && typeof bValue === 'string') {
        const comparison = aValue.toLowerCase().localeCompare(bValue.toLowerCase())
        return sortConfig.value.direction === 'asc' ? comparison : -comparison
      }

      // Handle number comparison
      if (typeof aValue === 'number' && typeof bValue === 'number') {
        return sortConfig.value.direction === 'asc' ? aValue - bValue : bValue - aValue
      }

      // Handle date comparison for order_date
      if (sortConfig.value.key === 'order_date') {
        const aDate = aValue ? new Date(aValue as string).getTime() : 0
        const bDate = bValue ? new Date(bValue as string).getTime() : 0
        return sortConfig.value.direction === 'asc' ? aDate - bDate : bDate - aDate
      }

      return 0
    })
  }

  return items
})

const pagination = usePagination(sortedAndFilteredItems)

// Reset to first page when filters change
watch([searchQuery, showOrderedOnly], () => {
  pagination.resetToFirstPage()
})

// Table column configuration
const tableColumns = [
  { key: 'item_name', label: 'Item Name', sortable: true },
  { key: 'quantity', label: 'Current Stock', sortable: true },
  { key: 'remark', label: 'Remark', sortable: true },
  { key: 'actions', label: 'Actions', sortable: false },
]

// Sorting functions
const toggleSort = (key: string): void => {
  if (sortConfig.value.key === key) {
    // Same column clicked - toggle direction
    sortConfig.value.direction = sortConfig.value.direction === 'asc' ? 'desc' : 'asc'
  } else {
    // New column clicked - set ascending
    sortConfig.value.key = key as keyof InventoryItem
    sortConfig.value.direction = 'asc'
  }
  pagination.resetToFirstPage()
}

// Action button configurations
const getItemActions = (item: InventoryItem): Array<ActionButtonGroupAction> => {
  const actions: Array<ActionButtonGroupAction> = [
    {
      key: 'edit-remark',
      label: 'Edit Remark',
      variant: 'blue',
    },
  ]

  if (item.order_date) {
    // Item is already ordered - show clear date option
    actions.push({
      key: 'clear-date',
      label: 'Clear Date',
      variant: 'yellow',
    })
  } else if (item.non_order_reason) {
    // Item has a reason - show change dropdown
    actions.push({
      key: 'change-action',
      label: 'Change',
      variant: 'orange',
      dropdown: [
        { key: 'mark-ordered', label: 'Mark Ordered' },
        { key: 'alternative-ordered', label: 'Alternative ordered' },
        { key: 'planning-to-order-later', label: 'Planning to order later' },
        { key: 'supplier-no-stock', label: 'Supplier has no stock' },
        { key: 'clear-reason', label: 'Clear reason' },
      ],
    })
  } else {
    // No status - show dropdown to select action
    actions.push({
      key: 'select-action',
      label: 'Select Action',
      variant: 'green',
      dropdown: [
        { key: 'mark-ordered', label: 'Mark Ordered' },
        { key: 'alternative-ordered', label: 'Alternative ordered' },
        { key: 'planning-to-order-later', label: 'Planning to order later' },
        { key: 'supplier-no-stock', label: 'Supplier has no stock' },
      ],
    })
  }

  return actions
}

// Handle action button clicks
const handleActionClick = (actionKey: string, item: InventoryItem) => {
  switch (actionKey) {
    case 'edit-remark':
      openEditRemarkModal(item)
      break
    case 'mark-ordered':
      openOrderModal(item)
      break
    case 'clear-date':
      clearOrderDate(item.id)
      break
    case 'alternative-ordered':
      setItemNonOrderReason(item.id, 'Alternative ordered')
      break
    case 'planning-to-order-later':
      setItemNonOrderReason(item.id, 'Planning to order later')
      break
    case 'supplier-no-stock':
      setItemNonOrderReason(item.id, 'Supplier has no stock')
      break
    case 'clear-reason':
      clearItemNonOrderReason(item.id)
      break
  }
}

// Remark editing functions
const saveRemark = async (itemId: string): Promise<void> => {
  const item = inventoryStore.items.find((item) => item.id === itemId)
  if (!item) return

  const updatedItem: InventoryItem = {
    ...item,
    remark: newRemark.value.trim(),
    updated_at: new Date().toISOString(),
  }

  await inventoryStore.updateItem(itemId, updatedItem)
}

// ReasonBadge centralizes the presentation for non_order_reason
</script>

// src/routes/price-list/+page.svelte
<script lang="ts">
	import { untrack } from 'svelte'
	import { toast } from 'svelte-sonner'
	import CalendarIcon from '@lucide/svelte/icons/calendar'
	import ClockIcon from '@lucide/svelte/icons/clock'
	import PackageOpenIcon from '@lucide/svelte/icons/package-open'
	import PencilIcon from '@lucide/svelte/icons/pencil'
	import SearchIcon from '@lucide/svelte/icons/search'
	import XIcon from '@lucide/svelte/icons/x'
	import { caretAtEnd } from '$lib/attachments/focus'
	import ActionModal from '$lib/components/app/ActionModal.svelte'
	import MarkOrderedDialog from '$lib/components/app/MarkOrderedDialog.svelte'
	import OrderStatusMenu from '$lib/components/app/OrderStatusMenu.svelte'
	import PageHeader from '$lib/components/app/PageHeader.svelte'
	import ReasonBadge from '$lib/components/app/ReasonBadge.svelte'
	import SortHeader from '$lib/components/app/SortHeader.svelte'
	import type { SortState } from '$lib/components/app/sort'
	import ToneBadge from '$lib/components/app/ToneBadge.svelte'
	import { Button } from '$lib/components/ui/button'
	import * as Empty from '$lib/components/ui/empty'
	import * as Field from '$lib/components/ui/field'
	import * as InputGroup from '$lib/components/ui/input-group'
	import { Skeleton } from '$lib/components/ui/skeleton'
	import * as Table from '$lib/components/ui/table'
	import { Textarea } from '$lib/components/ui/textarea'
	import * as ToggleGroup from '$lib/components/ui/toggle-group'
	import * as Tooltip from '$lib/components/ui/tooltip'
	import { useErrorToast } from '$lib/composables/errorToast.svelte'
	import { createLoadMore } from '$lib/composables/loadMore.svelte'
	import { inventoryStore } from '$lib/stores/inventory.svelte'
	import type { InventoryItem } from '$lib/types/inventory'
	import { formatDate } from '$lib/utils/date'
	import { cn } from '$lib/utils'

	// ---------- Toolbar state ----------
	type Filter = 'all' | 'ordered' | 'reason' | 'none'
	type SortKey = 'item_name' | 'quantity' | 'order_status' | 'remark'

	const FILTERS: Array<{ value: Filter; label: string }> = [
		{ value: 'all', label: 'All' },
		{ value: 'ordered', label: 'On Order' },
		{ value: 'reason', label: 'With Reason' },
		{ value: 'none', label: 'No Status' },
	]

	let searchQuery = $state('')
	let searchInput = $state<HTMLInputElement | null>(null)
	let filter = $state<Filter>('all')
	let sort = $state<SortState<SortKey>>({ key: null, direction: 'asc' })

	useErrorToast(() => inventoryStore.error)

	const matchesFilter = (item: InventoryItem): boolean => {
		switch (filter) {
			case 'ordered':
				return !!item.order_date
			case 'reason':
				return !item.order_date && !!item.non_order_reason
			case 'none':
				return !item.order_date && !item.non_order_reason
			default:
				return true
		}
	}

	// On order first, then reasons, then nothing; within on order, by date
	const orderStatusValue = (item: InventoryItem): string | null => {
		if (item.order_date) return `0 ${item.order_date}`
		if (item.non_order_reason) return `1 ${item.non_order_reason}`
		return null
	}

	const quantityTone = (item: InventoryItem): 'danger' | 'warning' | null => {
		if (item.not_track) return null
		if (item.quantity === 0) return 'danger'
		if (item.quantity <= item.reorder_level) return 'warning'
		return null
	}

	const plural = (count: number, noun: string): string =>
		`${count} ${count === 1 ? noun : `${noun}s`}`

	const sortedItems = $derived.by((): InventoryItem[] => {
		const items = inventoryStore.searchItems(searchQuery).filter(matchesFilter)
		const key = sort.key
		if (!key) return items

		const dir = sort.direction === 'asc' ? 1 : -1
		const valueOf = (item: InventoryItem): string | number | null => {
			if (key === 'order_status') return orderStatusValue(item)
			if (key === 'remark') return item.remark || null
			return item[key]
		}
		return [...items].sort((a, b) => {
			const av = valueOf(a)
			const bv = valueOf(b)
			// Missing values always sort last
			if (av === null && bv === null) return 0
			if (av === null) return 1
			if (bv === null) return -1
			if (typeof av === 'string' && typeof bv === 'string') {
				return dir * av.toLowerCase().localeCompare(bv.toLowerCase())
			}
			if (typeof av === 'number' && typeof bv === 'number') return dir * (av - bv)
			return 0
		})
	})

	const list = createLoadMore(() => sortedItems)

	const toggleSort = (key: SortKey): void => {
		if (sort.key === key) {
			sort.direction = sort.direction === 'asc' ? 'desc' : 'asc'
		} else {
			sort = { key, direction: 'asc' }
		}
	}

	// A new search, filter or sort starts the list from the top again
	$effect(() => {
		void searchQuery
		void filter
		void sort.key
		void sort.direction
		untrack(() => list.reset())
	})

	const isFiltered = $derived(searchQuery !== '' || filter !== 'all')
	const clearFilters = (): void => {
		searchQuery = ''
		filter = 'all'
	}

	// ⌥⌘F focuses the search field
	const onKeydown = (event: KeyboardEvent): void => {
		if (event.metaKey && event.altKey && event.code === 'KeyF') {
			event.preventDefault()
			searchInput?.focus()
			searchInput?.select()
		}
	}

	// ---------- Mark ordered ----------
	let orderDialog = $state<MarkOrderedDialog | null>(null)

	// ---------- Edit remark ----------
	let showRemarkDialog = $state(false)
	let remarkItem = $state<InventoryItem | null>(null)
	let remark = $state('')

	const isRemarkChanged = $derived(
		remarkItem !== null && remark.trim() !== (remarkItem.remark || '').trim(),
	)

	const openRemark = (item: InventoryItem): void => {
		remarkItem = item
		remark = item.remark || ''
		showRemarkDialog = true
	}

	const closeRemark = (): void => {
		showRemarkDialog = false
		remarkItem = null
	}

	const confirmRemark = async (): Promise<void> => {
		if (!remarkItem || !isRemarkChanged) return
		const item = remarkItem
		await inventoryStore.updateItem(item.id, { remark: remark.trim() })
		if (!inventoryStore.error) {
			toast.success(`Saved the remark of ${item.item_name}`)
			closeRemark()
		}
	}

	const initialLoading = $derived(inventoryStore.loading && inventoryStore.items.length === 0)
</script>

<svelte:window onkeydown={onKeydown} />

<PageHeader title="Price List">
	<div class="flex min-w-0 flex-1 flex-wrap items-center gap-2">
		<InputGroup.Root class="w-full sm:w-96">
			<InputGroup.Addon>
				<SearchIcon />
			</InputGroup.Addon>
			<InputGroup.Input
				bind:ref={searchInput}
				bind:value={searchQuery}
				type="search"
				placeholder="Search by item name"
				aria-label="Search by item name"
			/>
			{#if searchQuery}
				<InputGroup.Addon align="inline-end">
					<InputGroup.Button
						size="icon-sm"
						aria-label="Clear search"
						onclick={() => (searchQuery = '')}
					>
						<XIcon />
					</InputGroup.Button>
				</InputGroup.Addon>
			{/if}
		</InputGroup.Root>
		<ToggleGroup.Root
			type="single"
			variant="outline"
			value={filter}
			onValueChange={(value) => (filter = (value || 'all') as Filter)}
			aria-label="Filter by order status"
		>
			{#each FILTERS as option (option.value)}
				<ToggleGroup.Item value={option.value}>{option.label}</ToggleGroup.Item>
			{/each}
		</ToggleGroup.Root>
	</div>
</PageHeader>

{#if initialLoading}
	<Table.Root>
		<Table.Header>
			<Table.Row>
				<Table.Head>Item</Table.Head>
				<Table.Head>On hand</Table.Head>
				<Table.Head>Order status</Table.Head>
				<Table.Head class="w-[38%]">Remark</Table.Head>
				<Table.Head><span class="sr-only">Actions</span></Table.Head>
			</Table.Row>
		</Table.Header>
		<Table.Body>
			{#each { length: 8 } as _, i (i)}
				<Table.Row>
					<Table.Cell class="py-3"><Skeleton class="h-4 w-48" /></Table.Cell>
					<Table.Cell><Skeleton class="h-4 w-20" /></Table.Cell>
					<Table.Cell><Skeleton class="h-4 w-28" /></Table.Cell>
					<Table.Cell><Skeleton class="h-4 w-64" /></Table.Cell>
					<Table.Cell><Skeleton class="ms-auto h-7 w-32" /></Table.Cell>
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
{:else if sortedItems.length === 0}
	<Empty.Root class="my-auto">
		<Empty.Header>
			<Empty.Media variant="icon">
				<PackageOpenIcon />
			</Empty.Media>
			<Empty.Title>{isFiltered ? 'No items match' : 'No items yet'}</Empty.Title>
			<Empty.Description>
				{isFiltered
					? 'Try another search or clear the filter.'
					: 'Items added in Inventory appear here with their order status and remarks.'}
			</Empty.Description>
		</Empty.Header>
		<Empty.Content>
			{#if isFiltered}
				<Button variant="outline" onclick={clearFilters}>Clear Search</Button>
			{:else}
				<Button href="/inventory">Go to Inventory</Button>
			{/if}
		</Empty.Content>
	</Empty.Root>
{:else}
	<Table.Root>
		<Table.Header>
			<Table.Row>
				<SortHeader key="item_name" {sort} onsort={toggleSort}>Item</SortHeader>
				<SortHeader key="quantity" {sort} onsort={toggleSort}>On hand</SortHeader>
				<SortHeader key="order_status" {sort} onsort={toggleSort}>Order status</SortHeader>
				<SortHeader key="remark" {sort} onsort={toggleSort} class="w-[38%]">Remark</SortHeader>
				<Table.Head><span class="sr-only">Actions</span></Table.Head>
			</Table.Row>
		</Table.Header>
		<Table.Body>
			{#each list.visible as item (item.id)}
				{@const tone = quantityTone(item)}
				<Table.Row>
					<Table.Cell class="max-w-md min-w-48 py-2.5 font-medium break-words whitespace-normal">
						{item.item_name}
					</Table.Cell>
					<Table.Cell
						class={cn(
							'py-2.5 tabular-nums',
							tone === 'danger' && 'text-destructive font-semibold',
							tone === 'warning' && 'text-warning font-semibold',
						)}
					>
						{item.quantity}
						{item.unit}
					</Table.Cell>
					<Table.Cell class="py-2.5">
						{#if item.order_date}
							<ToneBadge tone="info">
								{#if item.back_order}
									<ClockIcon />
									Back-ordered {formatDate(item.order_date)}
								{:else}
									<CalendarIcon />
									Ordered {formatDate(item.order_date)}
								{/if}
							</ToneBadge>
						{:else if item.non_order_reason}
							<ReasonBadge reason={item.non_order_reason} size="md" />
						{:else}
							<span class="text-muted-foreground">—</span>
						{/if}
					</Table.Cell>
					<Table.Cell class="py-2.5 whitespace-normal">
						{#if item.remark}
							<div class="text-foreground/80 break-words whitespace-pre-wrap">{item.remark}</div>
						{:else}
							<span class="text-muted-foreground">No remark</span>
						{/if}
					</Table.Cell>
					<Table.Cell class="py-2.5">
						<div class="flex justify-end gap-1">
							<OrderStatusMenu {item} onMarkOrdered={(target) => orderDialog?.open(target)} />
							<Tooltip.Root>
								<Tooltip.Trigger>
									{#snippet child({ props })}
										<Button
											{...props}
											variant="ghost"
											size="icon-sm"
											aria-label="Edit Remark…"
											onclick={() => openRemark(item)}
										>
											<PencilIcon />
										</Button>
									{/snippet}
								</Tooltip.Trigger>
								<Tooltip.Content>Edit remark</Tooltip.Content>
							</Tooltip.Root>
						</div>
					</Table.Cell>
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
	<div class="text-muted-foreground flex items-center justify-between gap-3 text-sm">
		<span>Showing {list.shown} of {plural(list.total, 'item')}</span>
		{#if list.hasMore}
			<Button variant="outline" size="sm" onclick={list.loadMore}>Load More</Button>
		{/if}
	</div>
{/if}

<MarkOrderedDialog bind:this={orderDialog} />

<!-- Edit Remark -->
<ActionModal
	bind:open={showRemarkDialog}
	title={`Edit Remark · ${remarkItem?.item_name ?? ''}`}
	description="Last purchase price, supplier, or anything the next person ordering should know."
	loading={inventoryStore.loading}
	disabled={!isRemarkChanged}
	dirty={isRemarkChanged}
	confirmText="Save"
	onconfirm={confirmRemark}
	oncancel={closeRemark}
>
	<Field.Group>
		<Field.Field>
			<Field.Label for="remark">Remark</Field.Label>
			<Textarea
				id="remark"
				bind:value={remark}
				rows={3}
				placeholder="e.g. RM 32.00 per 100 · Pharmaniaga"
				{@attach caretAtEnd()}
			/>
		</Field.Field>
	</Field.Group>
</ActionModal>
